import "./globals.css"
import Link from "next/link"
import LoginBtn from "./LoginBtn.js"
import LogoutBtn from "./LogoutBtn.js"
import { getServerSession } from "next-auth"
import { authOptions } from "../pages/api/auth/[...NextAuth].js"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  const user = session?.user

  return (
    <html lang="en">
      <body>
        {user ? <LogoutBtn /> : <LoginBtn />}
        {user && user.image && <img src={user.image} height="15px" />}
        {user && user.name && <span>{user.name}</span>}

        <div className="navbar">
          <Link href="/" className="navbarItem">
            HOME
          </Link>
          <Link href="/bbs" className="navbarItem">
            BBS
          </Link>
        </div>

        {children}
      </body>
    </html>
  )
}
