export const MediaMovies = (state:any) => state.media.MediaMovie;
export const movieTags =(state:any) => state.media.moviestags;
export const tvShowsTags =(state:any) => state.media.tvShowsTags;
export const videoTags =(state:any) => state.media.videoTags;
export const upcommmingMovies = (state:any) => state.media.upcommmingMovies;
export const popularMovies = (state:any) => state.media.popularMovies;
export const latestMovies = (state:any) => state.media.latestMovies;
export const suggestedForYou = (state:any) => state.media.suggestedForYou;
export const bigSlider = (state:any) => state.media.bigSlider;
export const movieSlider = (state:any) => state.media.movieSlider;
export const movieOfTheYear = (state:any) => state.media.movieOfTheYear;
export const recommended = (state:any) => state.media.recommended;
export const relatedMovies = (state:any) => state.media.relatedMovies;
export const upcomming = (state:any) => state.media.upcomming;
export const pagination = (state:any) => state.media.pagination;
export const loadmoreup = (state:any) => state.media.loadmoreup;
export const loadmoredown = (state:any) => state.media.loadmoredown;
export const popularVideos = (state:any) => state.media.popularVideos;
export const specialsLatestVideos = (state:any) => state.media.specialsLatestVideos;
export const videosRecommendedForYou = (state:any) => state.media.videosRecommendedForYou;
export const videoSlider = (state:any) => state.media.videoSlider;
export const upcomingVideo = (state:any) => state.media.upcomingVideo;
export const tVPopularShows = (state:any) => state.media.tVPopularShows;
export const bestOfInternationalShows = (state:any) => state.media.bestOfInternationalShows;
export const suggestedTvShows = (state:any) => state.media.suggestedTvShows;
export const showsWeRecommend = (state:any) => state.media.showsWeRecommend;
export const tvShowSlider = (state:any) => state.media.tvShowSlider;
export const trendingSlider = (state:any) => state.media.trendingSlider;
export const cast = (state:any) => state.media.cast;