import { blogsDetails } from './blog-details';
import { generateImgPath } from './data';
export const filterBlog = (slug) => blogsGrid.find((item) => item.slug === slug);
export const filterBlogDetail = (slug) => blogsDetails.find((item) => item.slug === slug).detail;
export const dateWiseBlogs = (date) => blogs.filter((item) => item.blogDate.includes(date));
export const categoryWiseBlogs = (category) => blogs.filter((item) => item.categories.includes(category));
export const tagsWiseBlogs = (tag) => blogs.filter((item) => item.tags.includes(tag));

export const blogTags = [
  {
    id: 1,
    slug: 'drama',
    name: 'blogs.drama',
  },
  {
    id: 2,
    slug: 'action',
    name: 'home.action',
  },
  {
    id: 3,
    slug: 'comedies',
    name: 'home.comedy',
  },
  {
    id: 4,
    slug: 'drama',
    name: 'blogs.drama',
  },
  {
    id: 5,
    slug: 'dramas',
    name: 'blogs.drama',
  },
  {
    id: 6,
    slug: 'historical',
    name: 'blogs.history',
  },
  {
    id: 7,
    slug: 'horr',
    name: 'detail_page.horror',
  },
  {
    id: 8,
    slug: 'horror',
    name: 'detail_page.horror',
  },
  {
    id: 9,
    slug: 'movie',
    name: 'header.movie',
  },
  {
    id: 10,
    slug: 'movie-trailers',
    name: 'blogs.movie_trailers',
  },
  {
    id: 11,
    slug: 'mystery',
    name: 'ott_home.mystery',
  },
  {
    id: 12,
    slug: 'rumors',
    name: 'blogs.tv_rumors',
  },
  {
    id: 13,
    slug: 'thrill',
    name: 'ott_home.thriller',
  },
  {
    id: 14,
    slug: 'thriller',
    name: 'ott_home.thriller',
  },
  {
    id: 15,
    slug: 'trailer',
    name: 'home.trailers',
  },
  {
    id: 16,
    slug: 'tv rumors',
    name: 'blogs.tv_rumors',
  },
  {
    id: 17,
    slug: 'tv series',
    name: 'blogs.tv_series',
  },
];
export const blogCategories = [
  {
    id: 1,
    title: 'blogs.drama',
  },
  {
    id: 2,
    title: 'blogs.history',
  },
  {
    id: 3,
    title: 'blogs.movy',
  },
  {
    id: 4,
    title: 'blogs.movie_trailers',
  },
  {
    id: 5,
    title: 'blogs.trailers',
  },
  {
    id: 6,
    title: 'blogs.tv_comedies',
  },
  {
    id: 7,
    title: 'blogs.tv_rumors',
  },
  {
    id: 8,
    title: 'blogs.tv_series',
  },
];

export const blogs = [
  {
    id: 1,
    thumbnail: generateImgPath('/assets/images/blog/blog1.webp'),
    blogDate: 'February 2, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    slug: 'the-most-anticipated-movies',
    title: 'blogs.anticipated_movies',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    tags: ['comedy', 'drama', 'trailers'],
    month: 'February-2019',
  },
  {
    id: 2,
    thumbnail: generateImgPath('/assets/images/blog/blog2.webp'),
    blogDate: 'February 2, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    slug: 'amy-adams-always-dreamed',
    title: 'blogs.always_dreamed',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    tags: ['drama', 'trailers'],
    month: 'February-2019',
  },
  {
    id: 3,
    thumbnail: generateImgPath('/assets/images/blog/blog3.webp'),
    blogDate: 'February 2, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    slug: 'wandaVision-will-reveal-scarlet-witch’s-untapped-powers',
    title: 'blogs.wanda_vision',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movie_trailers',
    tags: ['horror', 'movie', 'movie trailers', 'thriller'],
    month: 'February-2019',
  },
  {
    id: 4,
    thumbnail: generateImgPath('/assets/images/blog/blog4.webp'),
    blogDate: '30 JAN 2019',
    userImage: generateImgPath('/assets/images/user/user1.webp'),
    username: 'blogs.jeni',
    title: 'blogs.everything_about',
    slug: 'everything-you-need-to-know-about',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('blog-template'),
    categories: 'blogs.tv_series',
    tags: ['comedy', 'movie trailers', 'trailers', 'tv series'],
    month: 'February-2019',
  },
  {
    id: 5,
    thumbnail: generateImgPath('/assets/images/blog/blog5.webp'),
    blogDate: 'February 2, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.black_pearl',
    slug: 'my-streaming-black-pearl',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movie_trailers',
    tags: ['movie trailers', 'mystery', 'thrill'],
    month: 'February-2019',
  },
  {
    id: 6,
    // thumbnail: '/assets/images/blog/02.webp',
    username: 'blogs.jeni',
    blogDate: 'February 1, 2019',
    title: 'blogs.personal_information',
    slug: 'what-personal-information-about-users',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    tags: ['horror ', 'movie', 'movie trailers'],
    month: 'February-2019',
  },
  {
    id: 7,
    thumbnail: generateImgPath('/assets/images/blog/blog7.webp'),
    blogDate: 'February 1, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.cookies_web',
    slug: 'cookies-and-web-beacons',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_comedies',
    tags: ['comedy', 'tv rumors', 'tv series'],
    month: 'February-2019',
  },
  {
    id: 8,
    thumbnail: generateImgPath('/assets/images/blog/blog8.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.birds_of_prey',
    slug: 'birds-Of-prey-star-says-she’s-definitely-open-to-a-ghost-return',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    tags: ['comedies', 'drama', 'horror', 'movie'],
    month: 'January-2019',
  },
  {
    id: 9,
    thumbnail: generateImgPath('/assets/images/blog/blog9.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.saturday_night',
    slug: 'saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.history',
    tags: ['historical', 'Movie', 'mystery'],
    month: 'January-2019',
  },
  {
    id: 10,
    thumbnail: generateImgPath('/assets/images/blog/blog10.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.gillian_shares',
    slug: 'gillian-anderson-shares-the-photos-from-the-crown',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    tags: ['comedies', 'movie trailers', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 11,
    thumbnail: generateImgPath('/assets/images/blog/blog2.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.chick_fight',
    slug: 'chick-fight’-felt-right-for-malin-akerman',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_series',
    tags: ['action', 'movie', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 12,
    thumbnail: generateImgPath('/assets/images/blog/12.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.amy_adams',
    slug: 'why-amy-adams-always-dreamed-of-working  ',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.history',
    tags: ['historical', 'movie', 'movie trailers'],
    month: 'January-2019',
  },
  {
    id: 13,
    thumbnail: generateImgPath('/assets/images/blog/blog2.webp'),
    blogDate: 'February 2, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.anticipated_tv_shows',
    slug: 'the-most-anticipated-tv-shows',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_rumors',
    tags: ['comedy', 'movie trailers', 'tv Rumors'],
    month: 'February-2019',
  },
  {
    id: 14,
    thumbnail: generateImgPath('/assets/images/blog/blog4.webp'),
    blogDate: 'january 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.cairo_station',
    slug: 'why-you-should-watch-cairo-station?',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    tags: ['action', 'drama', 'movie'],
    month: 'January-2019',
  },
  {
    id: 15,
    thumbnail: generateImgPath('/assets/images/blog/blog4.webp'),
    blogDate: 'january 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.everything_explained',
    slug: 'everything-you-need-to-know-about-‘sea’-season-3,-explained',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    tags: ['comedy', 'drama', 'movie'],
    month: 'January-2019',
  },
  {
    id: 16,
    thumbnail: generateImgPath('/assets/images/blog/05 (1).webp'),
    blogDate: 'january 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.easter_egg',
    slug: 'introduces-jodie-and-more-with-sweet-easter-egg',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    tags: ['action', 'movie', 'thriller'],
    month: 'January-2019',
  },
  {
    id: 17,
    thumbnail: generateImgPath('/assets/images/blog/05.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    slug: 'saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches',
    title: 'blogs.saturday_night',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_comedies',
    tags: ['action', 'historical', 'thrill', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 18,
    thumbnail: generateImgPath('/assets/images/blog/09.webp'),
    blogDate: 'january 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.cookies_web',
    slug: 'cookies-and-web-beacons',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    tags: ['action', 'dramas', 'horror', 'movies'],
    month: 'January-2019',
  },
  {
    id: 19,
    thumbnail: generateImgPath('/assets/images/blog/blog10.webp'),
    blogDate: 'january 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.gillian_photos',
    slug: 'gillian-anderson-shares-the-royal-behind-the-scenes-photos',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_rumors',
    tags: ['rumors', 'tv rumors', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 20,
    thumbnail: generateImgPath('/assets/images/blog/part-8.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.birds_of_prey',
    slug: 'birds-of-prey-star-says-she’s-definitely-open-to-a-ghost-return',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_series',
    tags: ['action', 'horror', 'movie', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 21,
    thumbnail: generateImgPath('/assets/images/blog/01-2.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.scarlett_backlash',
    slug: 'scarlett-drops-out-Of-playing-a-transgender-man-following-backlash',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_series',
    tags: ['action', 'thriller', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 22,
    thumbnail: generateImgPath('/assets/images/blog/movies06.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.villians_together',
    slug: 'first-glass-photos-bring-unbreakable-and-split-villians-together',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_rumors',
    tags: ['action', 'historical', 'tv rumors'],
    month: 'January-2019',
  },
  {
    id: 23,
    thumbnail: generateImgPath('/assets/images/blog/blog5.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.nhra_bristol',
    slug: 'nhra-at-bristol:-courtney-force-earns-7th-No.-1-spot-of-2018;',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_rumors',
    tags: ['action', 'tv rumors', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 24,
    thumbnail: generateImgPath('/assets/images/blog/another-danger.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.federee_wins',
    slug: 'federer-wins-maiden-stuttgart-title',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    tags: ['comedy', 'dramas', 'movie'],
    month: 'January-2019',
  },
  {
    id: 25,
    thumbnail: generateImgPath('/assets/images/blog/ep-8.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.record_setting_griefer',
    slug: 'record-setting-griefer-or-illain?',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_series',
    tags: ['action', 'thriller', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 26,
    thumbnail: generateImgPath('/assets/images/blog/movie.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.gta_six',
    slug: 'gta-vi-rumors-&-facts',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.history',
    tags: ['historical', 'movie', 'movie trailers'],
    month: 'January-2019',
  },
  {
    id: 27,
    thumbnail: generateImgPath('/assets/images/blog/12.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.thorin_slur',
    slug: 'thorin-used-anti-glay-Slur',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_comedies',
    tags: ['comedies', 'movie', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 28,
    thumbnail: generateImgPath('/assets/images/blog/11.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.free_game',
    slug: 'another-free-game-from-mazaon-games',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    tags: ['movie', 'movie trailer', 'thriller'],
    month: 'January-2019',
  },
  {
    id: 29,
    thumbnail: generateImgPath('/assets/images/blog/10.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.grab_free_skin',
    slug: 'grab-free-skin-and-loot-from-phone',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    tags: ['comedy', 'drama', 'movie'],
    month: 'January-2019',
  },
  {
    id: 30,
    thumbnail: generateImgPath('/assets/images/blog/09.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.drum_gum',
    slug: 'drum-gum-added-in-4.5-update',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.history',
    tags: ['historical', 'movie', 'mystery'],
    month: 'January-2019',
  },
  {
    id: 31,
    thumbnail: generateImgPath('/assets/images/blog/08.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.hot_wheels',
    slug: 'how-turned-hot-wheels-into-sheer-genius',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.trailer',
    tags: ['action', 'movie', 'trailers'],
    month: 'January-2019',
  },
  {
    id: 32,
    thumbnail: generateImgPath('/assets/images/blog/07.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    slug: 'island-2-is-still-in-deving-magic-confirms',
    title: 'blogs.island_2',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.trailer',
    tags: ['action', 'movie', 'thriller', 'trailers'],
    month: 'January-2019',
  },
  {
    id: 33,
    thumbnail: generateImgPath('/assets/images/blog/06.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.free_pc_game',
    slug: 'a-free-pc-game-is-still-available-through-ae',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movie_trailers',
    tags: ['movie', 'movie trailers', 'thriller'],
    month: 'January-2019',
  },
  {
    id: 34,
    thumbnail: generateImgPath('/assets/images/blog/05.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.free_gold',
    slug: '10-free-games-with-gold-of-July-2022-are-out',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    tags: ['movie', 'movie trailers', 'thriller'],
    month: 'January-2019',
  },
  {
    id: 35,
    thumbnail: generateImgPath('/assets/images/blog/04.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.merghani_league',
    slug: 'merghani-alonso-wins-eSport-league',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.history',
    tags: ['historical', 'movie', 'movie trailers'],
    month: 'January-2019',
  },
  {
    id: 36,
    thumbnail: generateImgPath('/assets/images/blog/blog1.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.soccer_2022',
    slug: '10-teams-we-cant-wait-to-use-in-soccer-2022',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.trailer',
    tags: ['action', 'thriller', 'trailers'],
    month: 'January-2019',
  },
  {
    id: 37,
    thumbnail: generateImgPath('/assets/images/blog/03.webp'),
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.racing_show',
    slug: 'racing-is-about-to-show-you-the-beauty-of-britain',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_series',
    tags: ['thriller', 'tv rumors', 'tv series'],
    month: 'January-2019',
  },
  {
    id: 38,
    thumbnail: generateImgPath('/assets/images/blog/blog2.webp'),
    blogDate: 'January 1, 2019',

    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.emmy_2018',
    slug: 'emmy-2018-game-of-throne-featured-having-22-nominee',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    tags: ['movie', 'movie trailer', 'thriller'],
    month: 'January-2019',
  },
];

export const blogsGrid = [
  {
    id: 1,
    slug: 'emmy-2018-game-of-throne-featured-having-22-nominee',
    title: 'blogs.emmy_2018',
    thumbnail: generateImgPath('/assets/images/blog/blog1.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    blogDate: 'January 1, 2019',

    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    month: 'january',
    tags: ['movie', 'movie trailer', 'thriller'],
  },
  {
    id: 2,
    slug: 'racing-is-about-to-show-you-the-beauty-of-britain',
    title: 'blogs.racing_show',
    thumbnail: generateImgPath('/assets/images/blog/blog2.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('audio-blog'),
    categories: 'blogs.tv_series',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['thriller', 'tv rumors', 'tv series'],
  },
  {
    id: 3,
    slug: '10-teams-we-cant-wait-to-use-in-soccer-2022',
    title: 'blogs.soccer_2022',
    thumbnail: generateImgPath('/assets/images/blog/blog3.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('video-blog'),
    categories: 'blogs.trailer',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'thriller', 'trailers'],
  },
  {
    id: 4,
    slug: 'merghani-alonso-wins-eSport-league',
    title: 'blogs.merghani_league',
    thumbnail: generateImgPath('/assets/images/blog/blog4.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('link-blog'),
    categories: 'blogs.History',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['historical', 'movie', 'movie trailers'],
  },
  {
    id: 5,
    slug: '10-free-games-with-gold-of-July-2022-are-out',
    title: 'blogs.free_gold',
    thumbnail: generateImgPath('/assets/images/blog/blog5.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('quote-blog'),
    categories: 'blogs.movy',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['movie', 'movie trailers', 'thriller'],
  },
  {
    id: 6,
    slug: 'a-free-pc-game-is-still-available-through-ae',
    title: 'blogs.free_pc_game',
    thumbnail: generateImgPath('/assets/images/blog/blog6.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('gallery-blog'),
    categories: 'blogs.movie_trailers',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['movie', 'movie trailers', 'thriller'],
  },
  {
    id: 7,
    slug: 'island-2-is-still-in-deving-magic-confirms',
    title: 'blogs.island_2',
    thumbnail: generateImgPath('/assets/images/blog/blog7.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.trailer',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'movie', 'thriller', 'trailers'],
  },
  {
    id: 8,
    slug: 'how-turned-hot-wheels-into-sheer-genius',
    title: 'blogs.hot_wheels',
    thumbnail: generateImgPath('/assets/images/blog/blog8.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.trailer',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'movie', 'trailers'],
  },
  {
    id: 9,
    slug: 'drum-gum-added-in-4.5-update',
    title: 'blogs.drum_gum',
    thumbnail: generateImgPath('/assets/images/blog/blog9.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.history',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['historical', 'movie', 'mystery'],
  },
  {
    id: 10,
    slug: 'grab-free-skin-and-loot-from-phone',
    title: 'blogs.grab_free_skin',
    thumbnail: generateImgPath('/assets/images/blog/blog10.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['comedy', 'drama', 'movie'],
  },
  {
    id: 11,
    slug: 'another-free-game-from-mazaon-games',
    title: 'blogs.free_game',
    thumbnail: generateImgPath('/assets/images/blog/blog11.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['movie', 'movie trailer', 'thriller'],
  },
  {
    id: 12,
    slug: 'thorin-used-anti-glay-Slur',
    title: 'blogs.thorin_slur',
    thumbnail: generateImgPath('/assets/images/blog/blog12.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_comedies',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['comedies', 'movie', 'tv series'],
  },
  {
    id: 13,
    slug: 'gta-vi-rumors-&-facts',
    title: 'blogs.gta_six',
    thumbnail: generateImgPath('/assets/images/blog/blog12.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.history',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['historical', 'movie', 'movie trailers'],
  },
  {
    id: 14,
    slug: 'record-setting-griefer-or-illain?',
    title: 'blogs.record_setting_griefer',
    thumbnail: generateImgPath('/assets/images/blog/blog1.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_series',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'thriller', 'tv series'],
  },
  {
    id: 15,
    slug: 'federer-wins-maiden-stuttgart-title',
    title: 'blogs.federee_wins',
    thumbnail: generateImgPath('/assets/images/blog/blog12.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit',
    categories: 'blogs.drama',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['comedy', 'dramas', 'movie'],
  },
  {
    id: 16,
    slug: 'nhra-at-bristol:-courtney-force-earns-7th-No.-1-spot-of-2018;',
    title: 'blogs.nhra_bristol',
    thumbnail: generateImgPath('/assets/images/blog/blog5.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_rumors',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'tv rumors', 'tv series'],
  },
  {
    id: 17,
    slug: 'first-glass-photos-bring-unbreakable-and-split-villians-together',
    title: 'blogs.villians_together',
    thumbnail: generateImgPath('/assets/images/blog/blog3.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_rumors',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'historical', 'tv rumors'],
  },
  {
    id: 18,
    slug: 'scarlett-drops-out-Of-playing-a-transgender-man-following-backlash',
    title: 'blogs.scarlett_backlash',
    thumbnail: generateImgPath('/assets/images/blog/blog1.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_series',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'thriller', 'tv series'],
  },
  {
    id: 19,
    slug: 'birds-of-prey-star-says-she’s-definitely-open-to-a-ghost-return',
    title: 'blogs.birds_of_prey',
    thumbnail: generateImgPath('/assets/images/blog/blog8.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_series',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'horror', 'movie', 'tv series'],
  },
  {
    id: 20,
    slug: 'gillian-anderson-shares-the-royal-behind-the-scenes-photos',
    title: 'blogs.gillian_photos',
    thumbnail: generateImgPath('/assets/images/blog/blog10.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_rumors',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['rumors', 'tv rumors', 'tv series'],
  },
  {
    id: 21,
    slug: 'cookies-and-web-beacons',
    title: 'blogs.cookies_web',
    thumbnail: generateImgPath('/assets/images/blog/blog9.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'dramas', 'horror', 'movies'],
  },
  {
    id: 22,
    slug: 'saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches',
    title: 'blogs.saturday_night',
    thumbnail: generateImgPath('/assets/images/blog/blog5.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_comedies',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'historical', 'thrill', 'tv series'],
  },
  {
    id: 23,
    slug: 'introduces-jodie-and-more-with-sweet-easter-egg',
    title: 'blogs.easter_egg',
    thumbnail: generateImgPath('/assets/images/blog/blog5.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'movie', 'thriller'],
  },
  {
    id: 24,
    slug: 'everything-you-need-to-know-about-‘sea’-season-3,-explained',
    title: 'blogs.everything_about',
    thumbnail: generateImgPath('/assets/images/blog/blog1.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['comedy', 'drama', 'movie'],
  },
  {
    id: 25,
    slug: 'why-you-should-watch-cairo-station?',
    title: 'blogs.cairo_station',
    thumbnail: generateImgPath('/assets/images/blog/blog1.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'drama', 'movie'],
  },
  {
    id: 26,
    slug: 'the-most-anticipated-tv-shows',
    title: 'blogs.anticipated_tv_shows',
    thumbnail: generateImgPath('/assets/images/blog/blog2.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_rumors',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['comedy', 'movie trailers', 'tv Rumors'],
  },
  {
    id: 27,
    thumbnail: generateImgPath('/assets/images/blog/blog1.webp'),
    blogDate: 'January 30, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    title: 'blogs.amy_adams',
    slug: 'why-amy-adams-always-dreamed-of-working  ',
    description: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.history',
    tags: ['historical', 'movie', 'movie trailers'],
  },
  {
    id: 28,
    slug: 'chick-fight’-felt-right-for-malin-akerman',
    title: 'blogs.chick_fight',
    thumbnail: generateImgPath('/assets/images/blog/blog2.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_series',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'movie', 'tv series'],
  },
  {
    id: 29,
    slug: 'gillian-anderson-shares-the-photos-from-the-crown',
    title: 'blogs.gillian_shares',
    thumbnail: generateImgPath('/assets/images/blog/blog10.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movy',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['rumors', 'tv rumors', 'tv series'],
  },
  {
    id: 30,
    slug: 'saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches',
    title: 'blogs.saturday_night',
    thumbnail: generateImgPath('/assets/images/blog/blog9.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.history',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'historical', 'thrill', 'tv series'],
  },
  {
    id: 31,
    slug: 'birds-Of-prey-star-says-she’s-definitely-open-to-a-ghost-return',
    title: 'blogs.birds_of_prey',
    thumbnail: generateImgPath('/assets/images/blog/blog8.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['comedies', 'drama', 'horror', 'movie'],
  },
  {
    id: 32,
    slug: 'cookies-and-web-beacons',
    title: 'blogs.cookies_web',
    thumbnail: generateImgPath('/assets/images/blog/blog7.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.tv_comedies',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['action', 'dramas', 'horror', 'movies'],
  },
  {
    id: 33,
    slug: 'what-personal-information-about-users',
    title: 'blogs.personal_information',
    thumbnail: generateImgPath('/assets/images/blog/blog7.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.Movy',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['horrow ', 'movie', 'movie trailers'],
  },
  {
    id: 34,
    slug: 'my-streaming-black-pearl',
    title: 'blogs.black_pearl',
    thumbnail: generateImgPath('/assets/images/blog/blog5.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movie_trailers',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['movie trailers', 'mystery', 'thrill'],
  },
  {
    id: 35,
    slug: 'everything-you-need-to-know-about',
    title: 'blogs.everything_about',
    thumbnail: generateImgPath('/assets/images/blog/blog4.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.trailer',
    blogDate: 'January 16, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['comedy', 'drama', 'movie'],
  },
  {
    id: 36,
    slug: 'wandaVision-will-reveal-scarlet-witch’s-untapped-powers',
    title: 'blogs.wanda_vision',
    thumbnail: generateImgPath('/assets/images/blog/blog3.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.movie_trailers',
    blogDate: 'February 2, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['horror', 'movie', 'movie trailers', 'thriller'],
  },
  {
    id: 37,
    slug: 'amy-adams-always-dreamed',
    title: 'blogs.always_dreamed',
    thumbnail: generateImgPath('/assets/images/blog/blog2.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    blogDate: 'February 2, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['drama', 'trailers'],
  },
  {
    id: 38,
    slug: 'the-most-anticipated-movies',
    title: 'blogs.anticipated_movies',
    thumbnail: generateImgPath('/assets/images/blog/blog1.webp'),
    shortDescription: 'Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.',
    longDescription: filterBlogDetail('simple-blog'),
    categories: 'blogs.drama',
    blogDate: 'February 2, 2019',
    userImage: generateImgPath('/assets/images/user/user3.webp'),
    username: 'blogs.jeni',
    tags: ['drama', 'trailers'],
  },
];
export const blogRecent = [filterBlog('the-most-anticipated-movies'), filterBlog('amy-adams-always-dreamed'), filterBlog('wandaVision-will-reveal-scarlet-witch’s-untapped-powers')].filter((item) => item !== undefined);
export const blogRecents = [filterBlog('the-most-anticipated-movies'), filterBlog('amy-adams-always-dreamed'), filterBlog('wandaVision-will-reveal-scarlet-witch’s-untapped-powers'), filterBlog('everything-you-need-to-know-about'), filterBlog('my-streaming-black-pearl')].filter((item) => item !== undefined);

// export const blogPagination = [filterBlog()]
