import { blogsDetails } from "./blog-details";

import { generateImgPath } from "./data";

export const filterBlog = (slug: string) =>
  blogsGrid.find((item) => item.slug === slug);

export const filterBlogDetail = (slug: string) =>
  blogsDetails.find((item) => item.slug === slug)?.detail;

export const dateWiseBlogs = (date: string) =>
  blogs.filter((item) => item.blogDate.includes(date));

export const categoryWiseBlogs = (category: string) =>
  blogs.filter((item) => item.categories.includes(category));

export const tagsWiseBlogs = (tag: string) =>
  blogs.filter((item) => item.tags.includes(tag));

export const blogTags = [
  {
    id: 1,
    slug: "drama",
    name: "Drama",
  },
  {
    id: 2,
    slug: "action",
    name: "Action",
  },
  {
    id: 3,
    slug: "comedies",
    name: "Comedy",
  },
  {
    id: 4,
    slug: "drama",
    name: "Drama",
  },
  {
    id: 5,
    slug: "dramas",
    name: "Dramas",
  },
  {
    id: 6,
    slug: "historical",
    name: "Historical",
  },
  {
    id: 7,
    slug: "horr",
    name: "Horr",
  },
  {
    id: 8,
    slug: "horror",
    name: "Horror",
  },
  {
    id: 9,
    slug: "movie",
    name: "Movie",
  },
  {
    id: 10,
    slug: "movie-trailers",
    name: "Movie Trailers",
  },
  {
    id: 11,
    slug: "mystery",
    name: "Mystery",
  },
  {
    id: 12,
    slug: "rumors",
    name: "Rumors",
  },
  {
    id: 13,
    slug: "thrill",
    name: "Thrill",
  },
  {
    id: 14,
    slug: "thriller",
    name: "Thriller",
  },
  {
    id: 15,
    slug: "trailer",
    name: "Trailer",
  },
  {
    id: 16,
    slug: "tv rumors",
    name: "Tv Rumors",
  },
  {
    id: 17,
    slug: "tv series",
    name: "Tv Series",
  },
];
export const blogCategories = [
  {
    id: 1,
    title: "drama",
    post_count: '4',
  },
  {
    id: 2,
    title: "historical",
    post_count: '7',
  },
  {
    id: 3,
    title: "movie",
    post_count: '2',
  },
  {
    id: 4,
    title: "movie trailers",
    post_count: '6',
  },
  {
    id: 5,
    title: "trailers",
    post_count: '4',
  },
  {
    id: 6,
    title: "tv comedies",
    post_count: '3',
  },
  {
    id: 7,
    title: "tv rumors",
    post_count: '4',
  },
  {
    id: 8,
    title: "tv series",
    post_count: '5',
  },
];

export const blogs = [
  {
    id: 1,
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    blogDate: "February 2, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    slug: "the-most-anticipated-movies",
    title: "The Most Anticipated Movies",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    tags: ["comedy", "drama", "trailers"],
    month: "February-2019",
  },
  {
    id: 2,
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    blogDate: "February 2, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    slug: "amy-adams-always-dreamed",
    title: "Amy Adams Always Dreamed",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    tags: ["drama", "trailers"],
    month: "February-2019",
  },
  {
    id: 3,
    thumbnail: generateImgPath("/assets/images/blog/blog3.webp"),
    blogDate: "February 2, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    slug: "wandaVision-will-reveal-scarlet-witch’s-untapped-powers",
    title: "WandaVision Will Reveal Scarlet Witch’s Untapped Powers",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie trailers",
    tags: ["horror", "movie", "movie trailers", "thriller"],
    month: "February-2019",
  },
  {
    id: 4,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "30 JAN 2019",
    userImage: "/assets/images/user/user1.webp",
    username: "goldenmace",
    title: "Everything You Need to Know About",
    slug: "everything-you-need-to-know-about",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("blog-template"),
    categories: "TV series",
    tags: ["comedy", "movie trailers", "trailers", "tv series"],
    month: "February-2019",
  },
  {
    id: 5,
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    blogDate: "February 2, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "My streaming Black Pearl",
    slug: "my-streaming-black-pearl",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie trailers",
    tags: ["movie trailers", "mystery", "thrill"],
    month: "February-2019",
  },
  {
    id: 6,
    thumbnail: generateImgPath("/assets/images/blog/blog6.webp"),
    username: "goldenmace",
    blogDate: "February 1, 2019",
    title: "What Personal Information About Users",
    slug: "what-personal-information-about-users",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    tags: ["horror ", "movie", "movie trailers"],
    month: "February-2019",
  },
  {
    id: 7,
    thumbnail: generateImgPath("/assets/images/blog/blog7.webp"),
    blogDate: "February 1, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Cookies and Web Beacons",
    slug: "cookies-and-web-beacons",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv comedies",
    tags: ["comedy", "tv rumors", "tv series"],
    month: "February-2019",
  },
  {
    id: 8,
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Birds Of Prey Star Says She’s Definitely Open To A Ghost Return",
    slug: "birds-Of-prey-star-says-she’s-definitely-open-to-a-ghost-return",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    tags: ["comedies", "drama", "horror", "movie"],
    month: "January-2019",
  },
  {
    id: 9,
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Saturday Night Live’ Re-Enacts Biden and Harris’ Victory Speeches",
    slug: "saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "historical",
    tags: ["historical", "Movie", "mystery"],
    month: "January-2019",
  },
  {
    id: 10,
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Gillian Anderson Shares the Photos From The Crown",
    slug: "gillian-anderson-shares-the-photos-from-the-crown",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    tags: ["comedies", "movie trailers", "tv series"],
    month: "January-2019",
  },
  {
    id: 11,
    thumbnail: generateImgPath("/assets/images/blog/02.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Chick Fight’ Felt Right For Malin Akerman",
    slug: "chick-fight’-felt-right-for-malin-akerman",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv series",
    tags: ["action", "movie", "tv series"],
    month: "January-2019",
  },
  {
    id: 12,
    thumbnail: generateImgPath("/assets/images/blog/12.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Why Amy Adams Always Dreamed of Working",
    slug: "why-amy-adams-always-dreamed-of-working  ",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "historical",
    tags: ["historical", "movie", "movie trailers"],
    month: "January-2019",
  },
  {
    id: 13,
    thumbnail: generateImgPath("/assets/images/blog/02.webp"),
    blogDate: "February 2, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "The Most Anticipated TV Shows",
    slug: "the-most-anticipated-tv-shows",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv rumors",
    tags: ["comedy", "movie trailers", "tv Rumors"],
    month: "February-2019",
  },
  {
    id: 14,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "january 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Why you should watch Cairo Station?",
    slug: "why-you-should-watch-cairo-station?",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    tags: ["action", "drama", "movie"],
    month: "January-2019",
  },
  {
    id: 15,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "january 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Everything You Need to Know About ‘sea’ Season 3, Explained",
    slug: "everything-you-need-to-know-about-‘sea’-season-3,-explained",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    tags: ["comedy", "drama", "movie"],
    month: "January-2019",
  },
  {
    id: 16,
    thumbnail: generateImgPath("/assets/images/blog/05 (1).webp"),
    blogDate: "january 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Introduces Jodie And More With Sweet Easter Egg",
    slug: "introduces-jodie-and-more-with-sweet-easter-egg",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    tags: ["action", "movie", "thriller"],
    month: "January-2019",
  },
  {
    id: 17,
    thumbnail: generateImgPath("/assets/images/blog/05.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    slug: "saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches",
    title: "Saturday Night Live’ Re-Enacts Biden and Harris’ Victory Speeches",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv comedies",
    tags: ["action", "historical", "thrill", "tv series"],
    month: "January-2019",
  },
  {
    id: 18,
    thumbnail: generateImgPath("/assets/images/blog/09.webp"),
    blogDate: "january 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Cookies and Web Beacons",
    slug: "cookies-and-web-beacons",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    tags: ["action", "dramas", "horror", "movies"],
    month: "January-2019",
  },
  {
    id: 19,
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    blogDate: "january 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Gillian Anderson Shares the Royal Behind-the-Scenes Photos",
    slug: "gillian-anderson-shares-the-royal-behind-the-scenes-photos",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv rumors",
    tags: ["rumors", "tv rumors", "tv series"],
    month: "January-2019",
  },
  {
    id: 20,
    thumbnail: generateImgPath("/assets/images/blog/part-8.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Birds Of Prey Star Says She’s Definitely Open To A Ghost Return",
    slug: "birds-of-prey-star-says-she’s-definitely-open-to-a-ghost-return",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv series",
    tags: ["action", "horror", "movie", "tv series"],
    month: "January-2019",
  },
  {
    id: 21,
    thumbnail: generateImgPath("/assets/images/blog/01-2.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Scarlett Drops Out Of Playing a Transgender Man Following Backlash",
    slug: "scarlett-drops-out-Of-playing-a-transgender-man-following-backlash",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv series",
    tags: ["action", "thriller", "tv series"],
    month: "January-2019",
  },
  {
    id: 22,
    thumbnail: generateImgPath("/assets/images/blog/movies06.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "First Glass Photos Bring Unbreakable and Split Villians Together",
    slug: "first-glass-photos-bring-unbreakable-and-split-villians-together",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv rumors",
    tags: ["action", "historical", "tv rumors"],
    month: "January-2019",
  },
  {
    id: 23,
    thumbnail: generateImgPath("/assets/images/blog/05 (1).webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "NHRA at Bristol: Courtney Force earns 7th No. 1 spot of 2018;",
    slug: "nhra-at-bristol:-courtney-force-earns-7th-No.-1-spot-of-2018;",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv rumors",
    tags: ["action", "tv rumors", "tv series"],
    month: "January-2019",
  },
  {
    id: 24,
    thumbnail: generateImgPath("/assets/images/blog/another-danger.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Federer wins maiden Stuttgart title",
    slug: "federer-wins-maiden-stuttgart-title",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "drama",
    tags: ["comedy", "dramas", "movie"],
    month: "January-2019",
  },
  {
    id: 25,
    thumbnail: generateImgPath("/assets/images/blog/ep-8.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Record-setting Griefer or Villain?",
    slug: "record-setting-griefer-or-illain?",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv series",
    tags: ["action", "thriller", "tv series"],
    month: "January-2019",
  },
  {
    id: 26,
    thumbnail: generateImgPath("/assets/images/blog/movie.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "GTA VI - Rumors & Facts",
    slug: "gta-vi-rumors-&-facts",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "historical",
    tags: ["historical", "movie", "movie trailers"],
    month: "January-2019",
  },
  {
    id: 27,
    thumbnail: generateImgPath("/assets/images/blog/12.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Thorin Used Anti-glay Slur",
    slug: "thorin-used-anti-glay-Slur",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv comedies",
    tags: ["comedies", "movie", "tv series"],
    month: "January-2019",
  },
  {
    id: 28,
    thumbnail: generateImgPath("/assets/images/blog/11.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Another free game from Mazaon Games",
    slug: "another-free-game-from-mazaon-games",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    tags: ["movie", "movie trailer", "thriller"],
    month: "January-2019",
  },
  {
    id: 29,
    thumbnail: generateImgPath("/assets/images/blog/10.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Grab free skin and loot From Phone",
    slug: "grab-free-skin-and-loot-from-phone",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    tags: ["comedy", "drama", "movie"],
    month: "January-2019",
  },
  {
    id: 30,
    thumbnail: generateImgPath("/assets/images/blog/09.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Drum Gum added in 4.5 Update",
    slug: "drum-gum-added-in-4.5-update",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "historical",
    tags: ["historical", "movie", "mystery"],
    month: "January-2019",
  },
  {
    id: 31,
    thumbnail: generateImgPath("/assets/images/blog/08.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "How turned Hot Wheels into sheer genius",
    slug: "how-turned-hot-wheels-into-sheer-genius",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "trailers",
    tags: ["action", "movie", "trailers"],
    month: "January-2019",
  },
  {
    id: 32,
    thumbnail: generateImgPath("/assets/images/blog/07.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    slug: "island-2-is-still-in-deving-magic-confirms",
    title: "Island 2 is still in deving, Magic confirms",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "trailers",
    tags: ["action", "movie", "thriller", "trailers"],
    month: "January-2019",
  },
  {
    id: 33,
    thumbnail: generateImgPath("/assets/images/blog/06.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "A Free PC Game is still available Through AE",
    slug: "a-free-pc-game-is-still-available-through-ae",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie trailers",
    tags: ["movie", "movie trailers", "thriller"],
    month: "January-2019",
  },
  {
    id: 34,
    thumbnail: generateImgPath("/assets/images/blog/05.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "10 Free Games with Gold of July 2019 are out",
    slug: "10-free-games-with-gold-of-July-2022-are-out",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    tags: ["movie", "movie trailers", "thriller"],
    month: "January-2019",
  },
  {
    id: 35,
    thumbnail: generateImgPath("/assets/images/blog/04.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Merghani Alonso wins eSport League",
    slug: "merghani-alonso-wins-eSport-league",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "historical",
    tags: ["historical", "movie", "movie trailers"],
    month: "January-2019",
  },
  {
    id: 36,
    thumbnail: generateImgPath("/assets/images/blog/01.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "10 teams we can't wait to use in Soccer 2022",
    slug: "10-teams-we-cant-wait-to-use-in-soccer-2022",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "trailers",
    tags: ["action", "thriller", "trailers"],
    month: "January-2019",
  },
  {
    id: 37,
    thumbnail: generateImgPath("/assets/images/blog/03.webp"),
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Racing is about to show you the beauty of Britain",
    slug: "racing-is-about-to-show-you-the-beauty-of-britain",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv series",
    tags: ["thriller", "tv rumors", "tv series"],
    month: "January-2019",
  },
  {
    id: 38,
    thumbnail: generateImgPath("/assets/images/blog/02.webp"),
    blogDate: "January 1, 2019",

    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Emmy 2018: “Game of Throne” featured having 22 nominee",
    slug: "emmy-2018-game-of-throne-featured-having-22-nominee",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    tags: ["movie", "movie trailer", "thriller"],
    month: "January-2019",
  },
];

export const blogsGrid = [
  {
    id: 1,
    slug: "emmy-2018-game-of-throne-featured-having-22-nominee",
    title: "Emmy 2018: “Game of Throne” featured having 22 nominee",
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    blogDate: "January 1, 2019",

    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    month: "january",
    tags: ["movie", "movie trailer", "thriller"],
  },
  {
    id: 2,
    slug: "racing-is-about-to-show-you-the-beauty-of-britain",
    title: "Racing is about to show you the beauty of Britain",
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("audio-blog"),
    categories: "tv series",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["thriller", "tv rumors", "tv series"],
  },
  {
    id: 3,
    slug: "10-teams-we-cant-wait-to-use-in-soccer-2022",
    title: "10 teams we can't wait to use in Soccer 2022",
    thumbnail: generateImgPath("/assets/images/blog/blog3.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("video-blog"),
    categories: "trailers",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "thriller", "trailers"],
  },
  {
    id: 4,
    slug: "merghani-alonso-wins-eSport-league",
    title: "Merghani Alonso wins eSport League",
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("link-blog"),
    categories: "Historical",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["historical", "movie", "movie trailers"],
  },
  {
    id: 5,
    slug: "10-free-games-with-gold-of-July-2022-are-out",
    title: "10 Free Games with Gold of July 2022 are out",
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("quote-blog"),
    categories: "movie",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["movie", "movie trailers", "thriller"],
  },
  {
    id: 6,
    slug: "a-free-pc-game-is-still-available-through-ae",
    title: "A Free PC Game is still available Through AE",
    thumbnail: generateImgPath("/assets/images/blog/blog6.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("gallery-blog"),
    categories: "movie trailers",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["movie", "movie trailers", "thriller"],
  },
  {
    id: 7,
    slug: "island-2-is-still-in-deving-magic-confirms",
    title: "Island 2 is still in deving, Magic confirms",
    thumbnail: generateImgPath("/assets/images/blog/blog7.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "trailers",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "movie", "thriller", "trailers"],
  },
  {
    id: 8,
    slug: "how-turned-hot-wheels-into-sheer-genius",
    title: "How turned Hot Wheels into sheer genius",
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "trailers",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "movie", "trailers"],
  },
  {
    id: 9,
    slug: "drum-gum-added-in-4.5-update",
    title: "Drum Gum added in 4.5 Update",
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "historical",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["historical", "movie", "mystery"],
  },
  {
    id: 10,
    slug: "grab-free-skin-and-loot-from-phone",
    title: "Grab free skin and loot From Phone",
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["comedy", "drama", "movie"],
  },
  {
    id: 11,
    slug: "another-free-game-from-mazaon-games",
    title: "Another free game from Mazaon Games",
    thumbnail: generateImgPath("/assets/images/blog/blog11.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["movie", "movie trailer", "thriller"],
  },
  {
    id: 12,
    slug: "thorin-used-anti-glay-Slur",
    title: "Thorin Used Anti-glay Slur",
    thumbnail: generateImgPath("/assets/images/blog/blog12.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv comedies",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["comedies", "movie", "tv series"],
  },
  {
    id: 13,
    slug: "gta-vi-rumors-&-facts",
    title: "GTA VI - Rumors & Facts",
    thumbnail: generateImgPath("/assets/images/blog/blog12.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "historical",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["historical", "movie", "movie trailers"],
  },
  {
    id: 14,
    slug: "record-setting-griefer-or-illain?",
    title: "Record-setting Griefer or Villain?",
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv series",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "thriller", "tv series"],
  },
  {
    id: 15,
    slug: "federer-wins-maiden-stuttgart-title",
    title: "Federer wins maiden Stuttgart title",
    thumbnail: generateImgPath("/assets/images/blog/blog12.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit",
    categories: "drama",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["comedy", "dramas", "movie"],
  },
  {
    id: 16,
    slug: "nhra-at-bristol:-courtney-force-earns-7th-No.-1-spot-of-2018;",
    title: "NHRA at Bristol: Courtney Force earns 7th No. 1 spot of 2018;",
    thumbnail: generateImgPath("/assets/images/blog/05 (1).webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv rumors",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "tv rumors", "tv series"],
  },
  {
    id: 17,
    slug: "first-glass-photos-bring-unbreakable-and-split-villians-together",
    title: "First Glass Photos Bring Unbreakable and Split Villians Together",
    thumbnail: generateImgPath("/assets/images/blog/movies06.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv rumors",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "historical", "tv rumors"],
  },
  {
    id: 18,
    slug: "scarlett-drops-out-Of-playing-a-transgender-man-following-backlash",
    title: "Scarlett Drops Out Of Playing a Transgender Man Following Backlash",
    thumbnail: generateImgPath("/assets/images/blog/01-2.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv series",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "thriller", "tv series"],
  },
  {
    id: 19,
    slug: "birds-of-prey-star-says-she’s-definitely-open-to-a-ghost-return",
    title: "Birds Of Prey Star Says She’s Definitely Open To A Ghost Return",
    thumbnail: generateImgPath("/assets/images/blog/part-8.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv series",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "horror", "movie", "tv series"],
  },
  {
    id: 20,
    slug: "gillian-anderson-shares-the-royal-behind-the-scenes-photos",
    title: "Gillian Anderson Shares the Royal Behind-the-Scenes Photos",
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv rumors",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["rumors", "tv rumors", "tv series"],
  },
  {
    id: 21,
    slug: "cookies-and-web-beacons",
    title: "Cookies and Web Beacons",
    thumbnail: generateImgPath("/assets/images/blog/09.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "drama",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "dramas", "horror", "movies"],
  },
  {
    id: 22,
    slug: "saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches",
    title: "Saturday Night Live’ Re-Enacts Biden and Harris’ Victory Speeches",
    thumbnail: generateImgPath("/assets/images/blog/05.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv comedies",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "historical", "thrill", "tv series"],
  },
  {
    id: 23,
    slug: "introduces-jodie-and-more-with-sweet-easter-egg",
    title: "Introduces Jodie And More With Sweet Easter Egg",
    thumbnail: generateImgPath("/assets/images/blog/05 (1).webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "movie", "thriller"],
  },
  {
    id: 24,
    slug: "everything-you-need-to-know-about-‘sea’-season-3,-explained",
    title: "Everything You Need to Know About ‘sea’ Season 3, Explained",
    thumbnail: generateImgPath("/assets/images/blog/1.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["comedy", "drama", "movie"],
  },
  {
    id: 25,
    slug: "why-you-should-watch-cairo-station?",
    title: "Why you should watch Cairo Station?",
    thumbnail: generateImgPath("/assets/images/blog/08.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "drama", "movie"],
  },
  {
    id: 26,
    slug: "the-most-anticipated-tv-shows",
    title: "The Most Anticipated TV Shows",
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv rumors",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["comedy", "movie trailers", "tv Rumors"],
  },
  {
    id: 27,
    thumbnail: generateImgPath("/assets/images/blog/12.webp"),
    blogDate: "January 30, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    title: "Why Amy Adams Always Dreamed of Working",
    slug: "why-amy-adams-always-dreamed-of-working  ",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "historical",
    tags: ["historical", "movie", "movie trailers"],
  },
  {
    id: 28,
    slug: "chick-fight’-felt-right-for-malin-akerman",
    title: "Chick Fight’ Felt Right For Malin Akerman",
    thumbnail: generateImgPath("/assets/images/blog/02.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv series",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "movie", "tv series"],
  },
  {
    id: 29,
    slug: "gillian-anderson-shares-the-photos-from-the-crown",
    title: "Gillian Anderson Shares the Photos From The Crown",
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["rumors", "tv rumors", "tv series"],
  },
  {
    id: 30,
    slug: "saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches",
    title: "Saturday Night Live’ Re-Enacts Biden and Harris’ Victory Speeches",
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "historical",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "historical", "thrill", "tv series"],
  },
  {
    id: 31,
    slug: "birds-Of-prey-star-says-she’s-definitely-open-to-a-ghost-return",
    title: "Birds Of Prey Star Says She’s Definitely Open To A Ghost Return",
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "drama",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["comedies", "drama", "horror", "movie"],
  },
  {
    id: 32,
    slug: "cookies-and-web-beacons",
    title: "Cookies and Web Beacons",
    thumbnail: generateImgPath("/assets/images/blog/blog7.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "tv comedies",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["action", "dramas", "horror", "movies"],
  },
  {
    id: 33,
    slug: "what-personal-information-about-users",
    title: "What Personal Information About Users",
    thumbnail: "",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "Movie",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["horrow ", "movie", "movie trailers"],
  },
  {
    id: 34,
    slug: "my-streaming-black-pearl",
    title: "My streaming Black Pearl",
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie trailers",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["movie trailers", "mystery", "thrill"],
  },
  {
    id: 35,
    slug: "everything-you-need-to-know-about",
    title: "Everything You Need to Know About",
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "trailers",
    blogDate: "January 16, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["comedy", "drama", "movie"],
  },
  {
    id: 36,
    slug: "wandaVision-will-reveal-scarlet-witch’s-untapped-powers",
    title: "WandaVision Will Reveal Scarlet Witch’s Untapped Powers",
    thumbnail: generateImgPath("/assets/images/blog/blog3.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "movie trailers",
    blogDate: "February 2, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["horror", "movie", "movie trailers", "thriller"],
  },
  {
    id: 37,
    slug: "amy-adams-always-dreamed",
    title: "Amy Adams Always Dreamed",
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    blogDate: "February 2, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["drama", "trailers"],
  },
  {
    id: 38,
    slug: "the-most-anticipated-movies",
    title: "The Most Anticipated Movies",
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "dramas",
    blogDate: "February 2, 2019",
    userImage: "/assets/images/user/user3.webp",
    username: "goldenmace",
    tags: ["drama", "trailers"],
  },
];
export const blogRecent = [
  filterBlog("the-most-anticipated-movies"),
  filterBlog("amy-adams-always-dreamed"),
  filterBlog("wandaVision-will-reveal-scarlet-witch’s-untapped-powers"),
].filter((item) => item !== undefined);
export const blogRecents = [
  filterBlog("the-most-anticipated-movies"),
  filterBlog("amy-adams-always-dreamed"),
  filterBlog("wandaVision-will-reveal-scarlet-witch’s-untapped-powers"),
  filterBlog("everything-you-need-to-know-about"),
  filterBlog("my-streaming-black-pearl"),
].filter((item) => item !== undefined);

// export const blogPagination = [filterBlog()]
