// Next.js에서 제공하는 Metadata 타입을 가져옴
import type { Metadata } from 'next'

// Google Fonts에서 제공하는 Geist 및 Geist_Mono 폰트를 가져옴
import { Geist, Geist_Mono } from 'next/font/google'

import Link from 'next/link'

// 글로벌 CSS 파일을 불러옴
import './globals.css'

// Geist Sans 폰트를 설정하고 CSS 변수(--font-geist-sans)를 지정
const geistSans = Geist({
  variable: '--font-geist-sans', // CSS에서 사용할 변수명
  subsets: ['latin'], // 사용할 문자 서브셋 (여기서는 라틴 문자)
})

// Geist Mono 폰트를 설정하고 CSS 변수(--font-geist-mono)를 지정
const geistMono = Geist_Mono({
  variable: '--font-geist-mono', // CSS에서 사용할 변수명
  subsets: ['latin'], // 사용할 문자 서브셋 (여기서는 라틴 문자)
})

// Next.js의 페이지 메타데이터 설정: SEO 대응을 여기서 할 수 있음.
export const metadata: Metadata = {
  title: 'Create Next App', // 페이지 제목
  description: 'Generated by create next app', // 페이지 설명
}

// RootLayout 컴포넌트 정의 (Next.js의 레이아웃 파일)
// 모든 페이지에서 공통적으로 적용되는 HTML 구조를 정의함
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode // 자식 요소를 받아서 렌더링함
}>) {
  return (
    <html lang="en">
      {/* 폰트 스타일을 적용하고 안티앨리어싱 효과를 활성화 */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 
          Layout:
            Header(Navigation, Breadcrumbs), SideBar(Search Bar), Footer, Popup(Modal=Dialog, Snackbar, Drawer),
            Toolbar, Tabs, Floating Component(Support, Guide, Tooltip, User Profile) 등.. 
        */}
        <header>
          <ul>
            <li>
              <Link href="/counter"><span className="font-bold text-lg">Counter</span></Link>
              / 
              <Link href="/movie-csr"><span className="font-bold text-lg">Movie-CSR</span></Link>
              /
              <Link href="/movie-ssr"><span className="font-bold text-lg">Movie-SSR</span></Link>
            </li>
          </ul>

        </header>

        {/* Page.tsx: 모든 하위 컴포넌트가 여기에 렌더링됨 */}
        <main>{children}</main>

        <footer>Footer</footer>
      </body>
    </html>
  )
}
