openapi: 3.0.0
info:
  version: 1.0.0
  title: Jsonplaceholder
  description: Jsonplaceholder TODO API
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://jsonplaceholder.typicode.com
paths:
  /todos/{id}:
    get:
      summary: 유저ID로 유저정보를 반환한다.
      parameters:
        - name : id # 사용자 id
          in: path # Url안에 있는 변수
          required: true
          description: 유저ID로 유저정보를 반환한다.
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                  id:
                    type: integer
                  title:
                    type: string
                  completed:
                    type: boolean
