import { blogsDetails } from "./blog-details";

import { generateImgPath } from "./data";

export const filterBlog = (slug) =>
  blogsGrid.find((item) => item.slug === slug);
export const filterBlogDetail = (slug) =>
  blogsDetails.find((item) => item.slug === slug).detail;
export const dateWiseBlogs = (date) =>
  blogs.filter((item) => item.blogDate.includes(date));
export const categoryWiseBlogs = (category) =>
  blogs.filter((item) => item.categories.includes(category));
export const tagsWiseBlogs = (tag) =>
  blogs.filter((item) => item.tags.includes(tag));

export const blogTags = [
  {
    id: 1,
    slug: "drama",
    name: "ott_home.drama",
  },
  {
    id: 2,
    slug: "action",
    name: "ott_home.action",
  },
  {
    id: 3,
    slug: "comedies",
    name: "blogs.comedy",
  },
  {
    id: 4,
    slug: "drama",
    name: "ott_home.drama",
  },
  {
    id: 5,
    slug: "dramas",
    name: "ott_home.drama",
  },
  {
    id: 6,
    slug: "historical",
    name: "ott_home.history",
  },
  {
    id: 7,
    slug: "horr",
    name: "ott_home.horror",
  },
  {
    id: 8,
    slug: "horror",
    name: "ott_home.horror",
  },
  {
    id: 9,
    slug: "movie",
    name: "blogs.movy",
  },
  {
    id: 10,
    slug: "movie-trailers",
    name: "blogs.movie_trailers",
  },
  {
    id: 11,
    slug: "mystery",
    name: "ott_home.mystery",
  },
  {
    id: 12,
    slug: "rumors",
    name: "blogs.tv_rumors",
  },
  {
    id: 13,
    slug: "thrill",
    name: "ott_home.thriller",
  },
  {
    id: 14,
    slug: "thriller",
    name: "ott_home.thriller",
  },
  {
    id: 15,
    slug: "trailer",
    name: "blogs.trailer",
  },
  {
    id: 16,
    slug: "tv rumors",
    name: "blogs.tv_rumors",
  },
  {
    id: 17,
    slug: "tv series",
    name: "blogs.tv_series",
  },
];
export const blogCategories = [
  {
    id: 1,
    title: "blogs.drama",
    post_count: "4",
  },
  {
    id: 2,
    title: "blogs.history",
    post_count: "7",
  },
  {
    id: 3,
    title: "blogs.movy",
    post_count: "2",
  },
  {
    id: 4,
    title: "blogs.movie_trailers",
    post_count: "6",
  },
  {
    id: 5,
    title: "blogs.trailer",
    post_count: "4",
  },
  {
    id: 6,
    title: "blogs.tv_comedies",
    post_count: "3",
  },
  {
    id: 7,
    title: "blogs.tv_rumors",
    post_count: "4",
  },
  {
    id: 8,
    title: "blogs.tv_series",
    post_count: "5",
  },
];

export const blogs = [
  {
    id: 1,
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    blogDate: "February 2, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    slug: "the-most-anticipated-movies",
    title: "blogs.anticipated_movies",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    tags: ["blogs.comedy", "blogs.drama", "blogs.trailer"],
    month: "February-2019",
  },
  {
    id: 2,
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    blogDate: "February 2, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    slug: "amy-adams-always-dreamed",
    title: "blogs.always_dreamed",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    tags: ["blogs.drama", "blogs.trailer"],
    month: "February-2019",
  },
  {
    id: 3,
    thumbnail: generateImgPath("/assets/images/blog/blog3.webp"),
    blogDate: "February 2, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    slug: "wandaVision-will-reveal-scarlet-witch’s-untapped-powers",
    title: "blogs.wanda_vision",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movie_trailers",
    tags: ["ott_home.horror", "blogs.movy", "blogs.movie_trailers", "ott_home.thriller"],
    month: "February-2019",
  },
  {
    id: 4,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "30 JAN 2019",
    userImage: generateImgPath("/assets/images/user/user1.webp"),
    username: "header.jenny",
    title: "blogs.everything_about",
    slug: "everything-you-need-to-know-about",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("blog-template"),
    categories: "blogs.tv_series",
    tags: ["blogs.comedy", "blogs.movie_trailers", "blogs.trailer", "blogs.tv_series"],
    month: "February-2019",
  },
  {
    id: 5,
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    blogDate: "February 2, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.black_pearl",
    slug: "my-streaming-black-pearl",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movie_trailers",
    tags: ["blogs.movie_trailers", "ott_home.mystery", "blogs.thrill"],
    month: "February-2019",
  },
  {
    id: 6,
    thumbnail: generateImgPath("/assets/images/blog/blog6.webp"),
    username: "header.jenny",
    blogDate: "February 1, 2019",
    title: "blogs.personal_information",
    slug: "what-personal-information-about-users",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    tags: ["ott_home.horror", "blogs.movy", "blogs.movie_trailers"],
    month: "February-2019",
  },
  {
    id: 7,
    thumbnail: generateImgPath("/assets/images/blog/blog7.webp"),
    blogDate: "February 1, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.cookies_web",
    slug: "cookies-and-web-beacons",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_comedies",
    tags: ["blogs.comedy", "blogs.tv_rumors", "blogs.tv_series"],
    month: "February-2019",
  },
  {
    id: 8,
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title:
      "blogs.birds_of_prey",
    slug: "birds-Of-prey-star-says-she’s-definitely-open-to-a-ghost-return",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    tags: ["ott_home.comedies", "blogs.drama", "ott_home.horror", "blogs.movy"],
    month: "January-2019",
  },
  {
    id: 9,
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title:
      "blogs.saturday_night",
    slug: "saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.history",
    tags: ["blogs.history", "blogs.movy", "ott_home.mystery"],
    month: "January-2019",
  },
  {
    id: 10,
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.gillian_shares",
    slug: "gillian-anderson-shares-the-photos-from-the-crown",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    tags: ["ott_home.comedies", "blogs.movie_trailers", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 11,
    thumbnail: generateImgPath("/assets/images/blog/02.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.chick_fight",
    slug: "chick-fight’-felt-right-for-malin-akerman",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_series",
    tags: ["episode_page.action", "blogs.movy", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 12,
    thumbnail: generateImgPath("/assets/images/blog/12.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.amy_adams",
    slug: "why-amy-adams-always-dreamed-of-working  ",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.history",
    tags: ["blogs.history", "blogs.movy", "blogs.movie_trailers"],
    month: "January-2019",
  },
  {
    id: 13,
    thumbnail: generateImgPath("/assets/images/blog/02.webp"),
    blogDate: "February 2, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.anticipated_tv_shows",
    slug: "the-most-anticipated-tv-shows",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_rumors",
    tags: ["blogs.comedy", "blogs.movie_trailers", "blogs.tv_rumors"],
    month: "February-2019",
  },
  {
    id: 14,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "january 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.cairo_station",
    slug: "why-you-should-watch-cairo-station?",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    tags: ["episode_page.action", "blogs.drama", "blogs.movy"],
    month: "January-2019",
  },
  {
    id: 15,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "january 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.everything_explained",
    slug: "everything-you-need-to-know-about-‘sea’-season-3,-explained",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    tags: ["blogs.comedy", "blogs.drama", "blogs.movy"],
    month: "January-2019",
  },
  {
    id: 16,
    thumbnail: generateImgPath("/assets/images/blog/05 (1).webp"),
    blogDate: "january 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.easter_egg",
    slug: "introduces-jodie-and-more-with-sweet-easter-egg",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    tags: ["episode_page.action", "blogs.movy", "ott_home.thriller"],
    month: "January-2019",
  },
  {
    id: 17,
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    slug: "saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches",
    title:
      "blogs.saturday_night",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_comedies",
    tags: ["episode_page.action", "blogs.history", "blogs.thrill", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 18,
    thumbnail: generateImgPath("/assets/images/blog/09.webp"),
    blogDate: "january 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.cookies_web",
    slug: "cookies-and-web-beacons",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    tags: ["episode_page.action", "blogs.drama", "ott_home.horror", "details_page.movies"],
    month: "January-2019",
  },
  {
    id: 19,
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    blogDate: "january 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.gillian_shares",
    slug: "gillian-anderson-shares-the-royal-behind-the-scenes-photos",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_rumors",
    tags: ["blogs.rumors", "blogs.tv_rumors", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 20,
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title:
      "blogs.birds_of_prey",
    slug: "birds-of-prey-star-says-she’s-definitely-open-to-a-ghost-return",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_series",
    tags: ["episode_page.action", "ott_home.horror", "blogs.movy", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 21,
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title:
      "blogs.scarlett_backlash",
    slug: "scarlett-drops-out-Of-playing-a-transgender-man-following-backlash",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_series",
    tags: ["episode_page.action", "ott_home.thriller", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 22,
    thumbnail: generateImgPath("/assets/images/blog/blog6.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title:
      "blogs.villians_together",
    slug: "first-glass-photos-bring-unbreakable-and-split-villians-together",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_rumors",
    tags: ["episode_page.action", "blogs.history", "blogs.tv_rumors"],
    month: "January-2019",
  },
  {
    id: 23,
    thumbnail: generateImgPath("/assets/images/blog/05 (1).webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.nhra_bristol",
    slug: "nhra-at-bristol:-courtney-force-earns-7th-No.-1-spot-of-2018;",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_rumors",
    tags: ["episode_page.action", "blogs.tv_rumors", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 24,
    thumbnail: generateImgPath("/assets/images/blog/blog3.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.federee_wins",
    slug: "federer-wins-maiden-stuttgart-title",
    description:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    tags: ["blogs.comedy", "blogs.drama", "blogs.movy"],
    month: "January-2019",
  },
  {
    id: 25,
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.record_setting_griefer",
    slug: "record-setting-griefer-or-illain?",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_series",
    tags: ["episode_page.action", "ott_home.thriller", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 26,
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.gta_six",
    slug: "gta-vi-rumors-&-facts",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.history",
    tags: ["blogs.history", "blogs.movy", "blogs.movie_trailers"],
    month: "January-2019",
  },
  {
    id: 27,
    thumbnail: generateImgPath("/assets/images/blog/12.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.thorin_slur",
    slug: "thorin-used-anti-glay-Slur",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_comedies",
    tags: ["ott_home.comedies", "blogs.movy", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 28,
    thumbnail: generateImgPath("/assets/images/blog/blog11.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.free_game",
    slug: "another-free-game-from-mazaon-games",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    tags: ["blogs.movy", "movie trailer", "ott_home.thriller"],
    month: "January-2019",
  },
  {
    id: 29,
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.grab_free_skin",
    slug: "grab-free-skin-and-loot-from-phone",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.dramas",
    tags: ["blogs.comedy", "blogs.drama", "blogs.movy"],
    month: "January-2019",
  },
  {
    id: 30,
    thumbnail: generateImgPath("/assets/images/blog/09.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.drum_gum",
    slug: "drum-gum-added-in-4.5-update",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.history",
    tags: ["blogs.history", "blogs.movy", "ott_home.mystery"],
    month: "January-2019",
  },
  {
    id: 31,
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.hot_wheels",
    slug: "how-turned-hot-wheels-into-sheer-genius",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.trailer",
    tags: ["episode_page.action", "blogs.movy", "blogs.trailer"],
    month: "January-2019",
  },
  {
    id: 32,
    thumbnail: generateImgPath("/assets/images/blog/blog7.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    slug: "island-2-is-still-in-deving-magic-confirms",
    title: "blogs.island_2",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.trailer",
    tags: ["episode_page.action", "blogs.movy", "ott_home.thriller", "blogs.trailer"],
    month: "January-2019",
  },
  {
    id: 33,
    thumbnail: generateImgPath("/assets/images/blog/blog6.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.free_pc_game",
    slug: "a-free-pc-game-is-still-available-through-ae",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movie_trailers",
    tags: ["blogs.movy", "blogs.movie_trailers", "ott_home.thriller"],
    month: "January-2019",
  },
  {
    id: 34,
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.soccer_2022",
    slug: "10-free-games-with-gold-of-July-2022-are-out",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    tags: ["blogs.movy", "blogs.movie_trailers", "ott_home.thriller"],
    month: "January-2019",
  },
  {
    id: 35,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.merghani_league",
    slug: "merghani-alonso-wins-eSport-league",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.history",
    tags: ["blogs.history", "blogs.movy", "blogs.movie_trailers"],
    month: "January-2019",
  },
  {
    id: 36,
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.soccer_2022",
    slug: "10-teams-we-cant-wait-to-use-in-soccer-2022",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.trailer",
    tags: ["episode_page.action", "ott_home.thriller", "blogs.trailer"],
    month: "January-2019",
  },
  {
    id: 37,
    thumbnail: generateImgPath("/assets/images/blog/blog3.webp"),
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.racing_show",
    slug: "racing-is-about-to-show-you-the-beauty-of-britain",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_series",
    tags: ["ott_home.thriller", "blogs.tv_rumors", "blogs.tv_series"],
    month: "January-2019",
  },
  {
    id: 38,
    thumbnail: generateImgPath("/assets/images/blog/02.webp"),
    blogDate: "January 1, 2019",

    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.emmy_2018",
    slug: "emmy-2018-game-of-throne-featured-having-22-nominee",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    tags: ["blogs.movy", "movie trailer", "ott_home.thriller"],
    month: "January-2019",
  },
];

export const blogsGrid = [
  {
    id: 1,
    slug: "emmy-2018-game-of-throne-featured-having-22-nominee",
    title: "blogs.emmy_2018",
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    blogDate: "January 1, 2019",

    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    month: "january",
    tags: ["blogs.movy", "movie trailer", "ott_home.thriller"],
  },
  {
    id: 2,
    slug: "racing-is-about-to-show-you-the-beauty-of-britain",
    title: "blogs.racing_show",
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("audio-blog"),
    categories: "blogs.tv_series",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["ott_home.thriller", "blogs.tv_rumors", "blogs.tv_series"],
  },
  {
    id: 3,
    slug: "10-teams-we-cant-wait-to-use-in-soccer-2022",
    title: "blogs.soccer_2022",
    thumbnail: generateImgPath("/assets/images/blog/blog3.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("video-blog"),
    categories: "blogs.trailer",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "ott_home.thriller", "blogs.trailer"],
  },
  {
    id: 4,
    slug: "merghani-alonso-wins-eSport-league",
    title: "blogs.merghani_league",
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("link-blog"),
    categories: "blogs.history",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.history", "blogs.movy", "blogs.movie_trailers"],
  },
  {
    id: 5,
    slug: "10-free-games-with-gold-of-July-2022-are-out",
    title: "blogs.soccer_2022",
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("quote-blog"),
    categories: "blogs.movy",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.movy", "blogs.movie_trailers", "ott_home.thriller"],
  },
  {
    id: 6,
    slug: "a-free-pc-game-is-still-available-through-ae",
    title: "blogs.free_pc_game",
    thumbnail: generateImgPath("/assets/images/blog/blog6.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("gallery-blog"),
    categories: "blogs.movie_trailers",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.movy", "blogs.movie_trailers", "ott_home.thriller"],
  },
  {
    id: 7,
    slug: "island-2-is-still-in-deving-magic-confirms",
    title: "blogs.island_2",
    thumbnail: generateImgPath("/assets/images/blog/blog7.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.trailer",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.movy", "ott_home.thriller", "blogs.trailer"],
  },
  {
    id: 8,
    slug: "how-turned-hot-wheels-into-sheer-genius",
    title: "blogs.hot_wheels",
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.trailer",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.movy", "blogs.trailer"],
  },
  {
    id: 9,
    slug: "drum-gum-added-in-4.5-update",
    title: "blogs.drum_gum",
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.history",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.history", "blogs.movy", "ott_home.mystery"],
  },
  {
    id: 10,
    slug: "grab-free-skin-and-loot-from-phone",
    title: "blogs.grab_free_skin",
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.comedy", "blogs.drama", "blogs.movy"],
  },
  {
    id: 11,
    slug: "another-free-game-from-mazaon-games",
    title: "blogs.free_game",
    thumbnail: generateImgPath("/assets/images/blog/blogblog11.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.movy", "movie trailer", "ott_home.thriller"],
  },
  {
    id: 12,
    slug: "thorin-used-anti-glay-Slur",
    title: "blogs.thorin_slur",
    thumbnail: generateImgPath("/assets/images/blog/blog12.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_comedies",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["ott_home.comedies", "blogs.movy", "blogs.tv_series"],
  },
  {
    id: 13,
    slug: "gta-vi-rumors-&-facts",
    title: "blogs.gta_six",
    thumbnail: generateImgPath("/assets/images/blog/blog12.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.history",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.history", "blogs.movy", "blogs.movie_trailers"],
  },
  {
    id: 14,
    slug: "record-setting-griefer-or-illain?",
    title: "blogs.record_setting_griefer",
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_series",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "ott_home.thriller", "blogs.tv_series"],
  },
  {
    id: 15,
    slug: "federer-wins-maiden-stuttgart-title",
    title: "blogs.federee_wins",
    thumbnail: generateImgPath("/assets/images/blog/blog12.webp"),
    shortDescription:
      "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit",
    categories: "blogs.drama",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.comedy", "blogs.drama", "blogs.movy"],
  },
  {
    id: 16,
    slug: "nhra-at-bristol:-courtney-force-earns-7th-No.-1-spot-of-2018;",
    title: "blogs.nhra_bristol",
    thumbnail: generateImgPath("/assets/images/blog/05 (1).webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_rumors",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.tv_rumors", "blogs.tv_series"],
  },
  {
    id: 17,
    slug: "first-glass-photos-bring-unbreakable-and-split-villians-together",
    title: "blogs.villians_together",
    thumbnail: generateImgPath("/assets/images/blog/blog6.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_rumors",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.history", "blogs.tv_rumors"],
  },
  {
    id: 18,
    slug: "scarlett-drops-out-Of-playing-a-transgender-man-following-backlash",
    title: "blogs.scarlett_backlash",
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_series",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "ott_home.thriller", "blogs.tv_series"],
  },
  {
    id: 19,
    slug: "birds-of-prey-star-says-she’s-definitely-open-to-a-ghost-return",
    title: "blogs.birds_of_prey",
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_series",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "ott_home.horror", "blogs.movy", "blogs.tv_series"],
  },
  {
    id: 20,
    slug: "gillian-anderson-shares-the-royal-behind-the-scenes-photos",
    title: "blogs.gillian_shares",
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_rumors",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.rumors", "blogs.tv_rumors", "blogs.tv_series"],
  },
  {
    id: 21,
    slug: "cookies-and-web-beacons",
    title: "blogs.cookies_web",
    thumbnail: generateImgPath("/assets/images/blog/09.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.drama", "ott_home.horror", "details_page.movies"],
  },
  {
    id: 22,
    slug: "saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches",
    title: "blogs.saturday_night",
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_comedies",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.history", "blogs.thrill", "blogs.tv_series"],
  },
  {
    id: 23,
    slug: "introduces-jodie-and-more-with-sweet-easter-egg",
    title: "blogs.easter_egg",
    thumbnail: generateImgPath("/assets/images/blog/05 (1).webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.movy", "ott_home.thriller"],
  },
  {
    id: 24,
    slug: "everything-you-need-to-know-about-‘sea’-season-3,-explained",
    title: "blogs.everything_explained",
    thumbnail: generateImgPath("/assets/images/blog/1.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.comedy", "blogs.drama", "blogs.movy"],
  },
  {
    id: 25,
    slug: "why-you-should-watch-cairo-station?",
    title: "blogs.cairo_station",
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.drama", "blogs.movy"],
  },
  {
    id: 26,
    slug: "the-most-anticipated-tv-shows",
    title: "blogs.anticipated_tv_shows",
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_rumors",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.comedy", "blogs.movie_trailers", "blogs.tv_rumors"],
  },
  {
    id: 27,
    thumbnail: generateImgPath("/assets/images/blog/12.webp"),
    blogDate: "January 30, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    title: "blogs.amy_adams",
    slug: "why-amy-adams-always-dreamed-of-working  ",
    description:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.history",
    tags: ["blogs.history", "blogs.movy", "blogs.movie_trailers"],
  },
  {
    id: 28,
    slug: "chick-fight’-felt-right-for-malin-akerman",
    title: "blogs.chick_fight",
    thumbnail: generateImgPath("/assets/images/blog/02.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_series",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.movy", "blogs.tv_series"],
  },
  {
    id: 29,
    slug: "gillian-anderson-shares-the-photos-from-the-crown",
    title: "blogs.gillian_shares",
    thumbnail: generateImgPath("/assets/images/blog/blog10.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.rumors", "blogs.tv_rumors", "blogs.tv_series"],
  },
  {
    id: 30,
    slug: "saturday-night-live’-re-enacts-biden-and-harris’-victory-speeches",
    title: "blogs.saturday_night",
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.history",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.history", "blogs.thrill", "blogs.tv_series"],
  },
  {
    id: 31,
    slug: "birds-Of-prey-star-says-she’s-definitely-open-to-a-ghost-return",
    title: "blogs.birds_of_prey",
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["ott_home.comedies", "blogs.drama", "ott_home.horror", "blogs.movy"],
  },
  {
    id: 32,
    slug: "cookies-and-web-beacons",
    title: "blogs.cookies_web",
    thumbnail: generateImgPath("/assets/images/blog/blog7.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.tv_comedies",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["episode_page.action", "blogs.drama", "ott_home.horror", "details_page.movies"],
  },
  {
    id: 33,
    slug: "what-personal-information-about-users",
    title: "blogs.personal_information",
    thumbnail: "",
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movy",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["ott_home.horror", "blogs.movy", "blogs.movie_trailers"],
  },
  {
    id: 34,
    slug: "my-streaming-black-pearl",
    title: "blogs.black_pearl",
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movie_trailers",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.movie_trailers", "ott_home.mystery", "blogs.thrill"],
  },
  {
    id: 35,
    slug: "everything-you-need-to-know-about",
    title: "Everything You Need to Know About",
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.trailer",
    blogDate: "January 16, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.comedy", "blogs.drama", "blogs.movy"],
  },
  {
    id: 36,
    slug: "wandaVision-will-reveal-scarlet-witch’s-untapped-powers",
    title: "blogs.wanda_vision",
    thumbnail: generateImgPath("/assets/images/blog/blog3.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.movie_trailers",
    blogDate: "February 2, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["ott_home.horror", "blogs.movy", "blogs.movie_trailers", "ott_home.thriller"],
  },
  {
    id: 37,
    slug: "amy-adams-always-dreamed",
    title: "blogs.always_dreamed",
    thumbnail: generateImgPath("/assets/images/blog/blog2.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    blogDate: "February 2, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.drama", "blogs.trailer"],
  },
  {
    id: 38,
    slug: "the-most-anticipated-movies",
    title: "blogs.anticipated_movies",
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    shortDescription:
      "blogs.blog_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "blogs.drama",
    blogDate: "February 2, 2019",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "header.jenny",
    tags: ["blogs.drama", "blogs.trailer"],
  },
];
export const blogRecent = [
  filterBlog("the-most-anticipated-movies"),
  filterBlog("amy-adams-always-dreamed"),
  filterBlog("wandaVision-will-reveal-scarlet-witch’s-untapped-powers"),
].filter((item) => item !== undefined);
export const blogRecents = [
  filterBlog("the-most-anticipated-movies"),
  filterBlog("amy-adams-always-dreamed"),
  filterBlog("wandaVision-will-reveal-scarlet-witch’s-untapped-powers"),
  filterBlog("everything-you-need-to-know-about"),
  filterBlog("my-streaming-black-pearl"),
].filter((item) => item !== undefined);

// export const blogPagination = [filterBlog()]
