<template>
  <div class="section-padding">
    <div class="container-fluid">
      <div class="row row-cols-2 row-cols-md-3 row-cols-lg-5">
        <div v-for="(data, index) in products" :key="index + data.product_name" class="col mb-5">
          <CardShopGridView :thumbnail="data.thumbnail" :slug="data.slug" :is-sale="data.is_sale" :is-new="data.is_new" :product-name="data.product_name" :price="data.price" :final-price="data.final_price" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import CardShopGridView from '../../components/merchandise/CategoryGridView.vue';
const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};
const products = [
  {
    id: 1,
    slug: 'bag-pack',
    product_name: 'shop.bag_pack',
    thumbnail: generateImgPath('/assets/images/shop/product/01.webp'),
    description: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.',
    stock_status: 'shop.in_stock',
    tags: ['costume', 'lighting'],
    sku: 'Bag Pack',
    discount: '',
    price: '$28.00',
    final_price: '$25.00',
    customer_review: 2,
    is_sale: true,
    is_new: false,
    rating: 4,
    additional_info: [
      {
        title: '',
        value: '',
        color: ['Green', 'Yellow'],
        size: ['L', 'M'],
      },
    ],
    created_at: '',
    category: ['merchandise.marvel_studios', 'Uptight-Birds'],
  },
  {
    id: 2,
    slug: 'believe-mask',
    product_name: 'shop.believe_mask',
    thumbnail: generateImgPath('/assets/images/shop/product/02.webp'),
    descriptio: 'shop.desc2',
    stock_status: 'shop.in_stock',
    tags: ['shop.camera', 'shop.costume', 'merchandise.studios'],
    sku: 'shop.mask',
    discount: '',
    price: '',
    final_price: '$13.00',
    customer_review: 0,
    is_sale: false,
    is_new: false,
    ratting: 0,
    additional_info: [
      {
        title: '',
        value: '',
        color: ['Gray'],
        size: ['M', 'S'],
      },
    ],
    created_at: '',
    category: ['merchandise.disney_world', 'merchandise.marvel_studios', 'merchandise.fantasia', 'merchandise.the_madrid'],
  },
  {
    id: 3,
    slug: 'black-bow',
    product_name: 'shop.black_bow',
    thumbnail: generateImgPath('/assets/images/shop/product/03.webp'),
    descriptio: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.',
    stock_status: 'shop.in_stock',
    tags: ['Lighting', 'merchandise.studios'],
    sku: 'logo-collection',
    discount: '',
    final_price: '$18.00 – $45.00',
    customer_review: 1,
    is_sale: true,
    is_new: false,
    ratting: 0,
    additional_info: [
      {
        title: '',
        value: '',
        color: [],
        size: ['M', 'S'],
      },
    ],
    created_at: '',
    category: ['Activeman', 'Avengers', 'Harry-David', 'Haunted-Halloween', 'merchandise.marvel_studios', 'merchandise.marvel_studios', 'Quid-Game', 'The-Flashv', 'Warner-Bros-Films'],
  },
  {
    id: 4,
    slug: 'black-cap',
    product_name: 'shop.black_cap',
    thumbnail: generateImgPath('/assets/images/shop/product/04.webp'),
    category: ['merchandise.marvel_studios', 'harry-david', 'warner-bro-films'],
    stock_status: 'shop.in_stock',
    descriptio: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable..',
    tags: ['shop.camera', 'Production'],
    sku: 'woo-beanie',
    discount: '',
    price: '$20.00',
    final_price: '$18.00',
    customer_review: 0,
    is_sale: false,
    is_new: true,
    ratting: 0,
    additional_info: [
      {
        title: '',
        value: '',
        color: ['Blue', 'Gray', 'Green', 'Red', 'Yellow'],
        size: ['l', 'm', 's'],
      },
    ],
    created_at: '',
  },
  {
    id: 5,
    slug: 'boxing-gloves',
    product_name: 'shop.boxing_gloves',
    thumbnail: generateImgPath('/assets/images/shop/product/05.webp'),
    descriptio: 'shop.desc2',
    stock_status: 'shop.in_stock',
    tags: ['shop.lightning', 'shop.production'],
    sku: 'Gloves',
    discount: '',
    price: '',
    final_price: '$17.00',
    customer_review: 1,
    is_sale: false,
    is_new: false,
    ratting: 5,
    additional_info: [
      {
        title: '',
        value: '',
        color: ['black', 'red', 'yellow'],
        size: ['l', 'm', 's'],
      },
    ],
    created_at: '',
    category: ['quid-game'],
  },
  {
    id: 6,
    slug: 'bag-pack',
    product_name: 'shop.bag_pack',
    thumbnail: generateImgPath('/assets/images/shop/product/01.webp'),
    description: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.',
    stock_status: 'shop.in_stock',
    tags: ['costume', 'lighting'],
    sku: 'Bag Pack',
    discount: '',
    price: '$28.00',
    final_price: '$25.00',
    customer_review: 2,
    is_sale: true,
    is_new: false,
    rating: 4,
    additional_info: [
      {
        title: '',
        value: '',
        color: ['Green', 'Yellow'],
        size: ['L', 'M'],
      },
    ],
    created_at: '',
    category: ['merchandise.marvel_studios', 'Uptight-Birds'],
  },
  {
    id: 7,
    slug: 'believe-mask',
    product_name: 'shop.believe_mask',
    thumbnail: generateImgPath('/assets/images/shop/product/02.webp'),
    descriptio: 'shop.desc2',
    stock_status: 'shop.in_stock',
    tags: ['shop.camera', 'shop.costume', 'merchandise.studios'],
    sku: 'shop.mask',
    discount: '',
    price: '',
    final_price: '$13.00',
    customer_review: 0,
    is_sale: false,
    is_new: false,
    ratting: 0,
    additional_info: [
      {
        title: '',
        value: '',
        color: ['Gray'],
        size: ['M', 'S'],
      },
    ],
    created_at: '',
    category: ['merchandise.disney_world', 'merchandise.marvel_studios', 'merchandise.fantasia', 'merchandise.the_madrid'],
  },
  {
    id: 8,
    slug: 'black-bow',
    product_name: 'shop.black_bow',
    thumbnail: generateImgPath('/assets/images/shop/product/03.webp'),
    descriptio: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable.',
    stock_status: 'shop.in_stock',
    tags: ['Lighting', 'merchandise.studios'],
    sku: 'logo-collection',
    discount: '',
    final_price: '$18.00 – $45.00',
    customer_review: 1,
    is_sale: true,
    is_new: false,
    ratting: 0,
    additional_info: [
      {
        title: '',
        value: '',
        color: [],
        size: ['M', 'S'],
      },
    ],
    created_at: '',
    category: ['Activeman', 'Avengers', 'Harry-David', 'Haunted-Halloween', 'merchandise.marvel_studios', 'merchandise.marvel_studios', 'Quid-Game', 'The-Flashv', 'Warner-Bros-Films'],
  },
  {
    id: 9,
    slug: 'black-cap',
    product_name: 'shop.black_cap',
    thumbnail: generateImgPath('/assets/images/shop/product/04.webp'),
    category: ['merchandise.marvel_studios', 'harry-david', 'warner-bros-films'],
    stock_status: 'shop.in_stock',
    descriptio: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly believable..',
    tags: ['shop.camera', 'Production'],
    sku: 'woo-beanie',
    discount: '',
    price: '$20.00',
    final_price: '$18.00',
    customer_review: 0,
    is_sale: false,
    is_new: true,
    ratting: 0,
    additional_info: [
      {
        title: '',
        value: '',
        color: ['Blue', 'Gray', 'Green', 'Red', 'Yellow'],
        size: ['l', 'm', 's'],
      },
    ],
    created_at: '',
  },
  {
    id: 10,
    slug: 'boxing-gloves',
    product_name: 'shop.boxing_gloves',
    thumbnail: generateImgPath('/assets/images/shop/product/05.webp'),
    descriptio: 'shop.desc2',
    stock_status: 'shop.in_stock',
    tags: ['shop.lightning', 'shop.production'],
    sku: 'Gloves',
    discount: '',
    price: '',
    final_price: '$17.00',
    customer_review: 1,
    is_sale: false,
    is_new: false,
    ratting: 5,
    additional_info: [
      {
        title: '',
        value: '',
        color: ['black', 'red', 'yellow'],
        size: ['l', 'm', 's'],
      },
    ],
    created_at: '',
    category: ['quid-game'],
  },
];
</script>
