import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import useTranslation from 'next-translate/useTranslation'
// 4. MUI 컴포넌트 Stack, Button 임포트
import { Stack, Button } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { t } = useTranslation()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <h2>{t('common:Japanese')}</h2>
          <h2>{t('common:English')}</h2>
          <h2>{t('common:Korean')}</h2>

          {/* 5. MUI 컴포넌트 Stack, Button 사용 */}
          <Stack spacing={2} direction="row">
            <Button variant="text">Text</Button>
            <Button variant="contained">Contained</Button>
            <Button variant="outlined">Outlined</Button>
          </Stack>
        </main>
      </div>
    </>
  )
}
