# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    # 이벤트 처리 메소드들 모음 START
    # 아래 메소드 1개 추가 : "아래 코드에서 지정했던" 이벤트 발생시의 슬롯(이벤트 처리) 구현부
    def btn_clicked(self):
        self.label.setText("클릭됨") # 슬롯 : 이벤트 처리
    # 이벤트 처리 메소드들 모음 END

    # UI 설정하기 START
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 20, 93, 28))
        self.pushButton.setObjectName("pushButton")

        # 아래 코드 1줄 추가 : 시그널(이벤트 지정) 구현부
        self.pushButton.clicked.connect(self.btn_clicked) # 시그널 : 이벤트 지정

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 62, 15))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    # UI 설정하기 END

    # UI 이름표시 설정 START
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # 아래 코드 1줄 수정 : 타이틀을 원하는 이름으로 바꿔주었다.
        MainWindow.setWindowTitle(_translate("MainWindow", "메인윈도우")) 
        self.pushButton.setText(_translate("MainWindow", "클릭"))
    # UI 이름표시 설정 END

# RUN 시에 실행할 것
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
