import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
// 1. next-translate 임포트
import useTransition from 'next-translate/useTranslation'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // 2. useTranstaion 함수를 이용해서 t 함수를 취득
  const { t } = useTransition()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>{t('common:Japanese')}</h2>
        <h2>{t('common:English')}</h2>
        <h2>{t('common:Korean')}</h2>
      </main>
    </>
  )
}
