export const MediaMovies = (state) => state.media.MediaMovie;
export const movieTags =(state) => state.media.moviestags;
export const tvShowsTags =(state) => state.media.tvShowsTags;
export const videoTags =(state) => state.media.videoTags;
export const upcommmingMovies = (state) => state.media.upcommmingMovies;
export const popularMovies = (state) => state.media.popularMovies;
export const latestMovies = (state) => state.media.latestMovies;
export const suggestedForYou = (state) => state.media.suggestedForYou;
export const bigSlider = (state) => state.media.bigSlider;
export const movieSlider = (state) => state.media.movieSlider;
export const movieOfTheYear = (state) => state.media.movieOfTheYear;
export const recommended = (state) => state.media.recommended;
export const relatedMovies = (state) => state.media.relatedMovies;
export const upcomming = (state) => state.media.upcomming;
export const pagination = (state) => state.media.pagination;
export const loadmoreup = (state) => state.media.loadmoreup;
export const loadmoredown = (state) => state.media.loadmoredown;
export const popularVideos = (state) => state.media.popularVideos;
export const specialsLatestVideos = (state) => state.media.specialsLatestVideos;
export const videosRecommendedForYou = (state) => state.media.videosRecommendedForYou;
export const videoSlider = (state) => state.media.videoSlider;
export const upcomingVideo = (state) => state.media.upcomingVideo;
export const tVPopularShows = (state) => state.media.tVPopularShows;
export const bestOfInternationalShows = (state) => state.media.bestOfInternationalShows;
export const suggestedTvShows = (state) => state.media.suggestedTvShows;
export const showsWeRecommend = (state) => state.media.showsWeRecommend;
export const tvShowSlider = (state) => state.media.tvShowSlider;
export const trendingSlider = (state) => state.media.trendingSlider;
export const cast = (state) => state.media.cast;